config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  resources :oauth_clients
  devise_for :users, sign_out_via: [:get, :delete]

  # SSO Provider routes
  match '/auth/sso/authorize' => 'auth#authorize', via: :all
  match '/auth/sso/access_token' => 'auth#access_token', via: :all
  match '/auth/sso/user' => 'auth#user', via: :all
  match '/oauth/token' => 'auth#access_token', via: :all

  root "dashboard#index"
end

app/models/access_grant.rb
class AccessGrant < ApplicationRecord
  belongs_to :user
  belongs_to :oauth_client

  before_create :generate_tokens

  # Generate random tokens
  def generate_tokens
    self.code = SecureRandom.hex(16)
    self.access_token = SecureRandom.hex(16)
    self.refresh_token = SecureRandom.hex(16)
  end

  # Delete all grants which are older than 3 days
  def self.prune!
    where("created_at < ?", 3.days.ago).delete_all
  end

  # Class method to find access grants by code and client ID
  def self.authenticate(code, application_id)
    AccessGrant.where("code = ? AND oauth_client_id = ?", code, application_id).first
  end

  # Instance method to dynamically define the redirect URI after an access grant is issued.
  def redirect_uri_for(redirect_uri)
    if redirect_uri =~ /\?/
      redirect_uri + "&code=#{code}&response_type=code&state=#{state}"
    else
      redirect_uri + "?code=#{code}&response_type=code&state=#{state}"
    end
  end

  # Note: This is currently configured through devise, and matches the AuthController access token life
  def start_expiry_period!
    self.update_attribute(:access_token_expires_at, Time.now + Devise.timeout_in)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/oauth_client.rb
class OauthClient < ApplicationRecord
  before_validation :set_attributes

  validates :name, :presence => true

  # Check whether a Client exists by app_id and app_secret
  def self.authenticate(app_id, app_secret)
    where(["app_id = ? AND app_secret = ?", app_id, app_secret]).first
  end

  private
    def set_attributes
      if new_record?
        generate_app_id!
        generate_app_secret!
      end
    end

    def generate_app_id!
      begin
        self.app_id = SecureRandom.hex
      end while self.class.exists?(app_id: app_id)
    end

    def generate_app_secret!
      begin
        self.app_secret = SecureRandom.hex
      end while self.class.exists?(app_secret: app_secret)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :access_grants, dependent: :delete_all

  def oauth_payload
    _hash = {
      provider: 'sso',
      id: self.id,
      info: {
         email: self.email,
         name: self.email, # TODO for you: Handle name and pass the data here
      },
      extra: {
        first_name: "TODO", # TODO for you: To pass the relevant data here
        last_name: "TODO", # TODO for you: To pass the relevant data here
        mobile_number: "123456789", # TODO for you: To pass the relevant data here
      }
    }
    return _hash
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  # This is our new function that comes before Devise's one

  before_action :authenticate_oauth_user!, :except => [:access_token]
  before_action :authenticate_user!, :except => [:access_token]
  skip_before_action :verify_authenticity_token, :only => [:access_token]

  def authorize
    # Note: this method will be called when the user
    # is logged into the provider
    #
    # So we're essentially granting him access to our
    # system by generating certain tokens and then
    # redirecting him back to the params[:redirect_uri]
    # with a random code and the params[:state]


    AccessGrant.prune!
    create_hash = {
      oauth_client: application,
      state: params[:state]
    }
    access_grant = current_user.access_grants.create(create_hash)
    redirect_to access_grant.redirect_uri_for(params[:redirect_uri]), allow_other_host: true
  end

  # POST
  def access_token
    access_grant = AccessGrant.find_by_code(params[:code])
    if access_grant.nil?
      render :json => {:error => "Could not authenticate with the access grant code"}
      return
    end

    application = access_grant.oauth_client
    if application.nil?
      render :json => {:error => "Could not find OAuth application"}
      return
    end

    access_grant.start_expiry_period!
    render :json => {:access_token => access_grant.access_token, :refresh_token => access_grant.refresh_token, :expires_in => Devise.timeout_in.to_i}
  end

  def user
    hash = current_user.oauth_payload
    render :json => hash.to_json
  end

  protected

  def application
    @application ||= OauthClient.find_by_app_id(params[:client_id])
  end

  private

  def authenticate_oauth_user!
    if params[:oauth_token]
      access_grant = AccessGrant.where(access_token: params[:oauth_token]).take
      if access_grant.user
        sign_in access_grant.user # Devise sign in
      end
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_oauth_client, only: %i[ show edit update destroy ]

  # GET /oauth_clients or /oauth_clients.json
  def index
    @oauth_clients = OauthClient.all
  end

  # GET /oauth_clients/1 or /oauth_clients/1.json
  def show
  end

  # GET /oauth_clients/new
  def new
    @oauth_client = OauthClient.new
  end

  # GET /oauth_clients/1/edit
  def edit
  end

  # POST /oauth_clients or /oauth_clients.json
  def create
    @oauth_client = OauthClient.new(oauth_client_params)

    respond_to do |format|
      if @oauth_client.save
        format.html { redirect_to oauth_client_url(@oauth_client), notice: "Oauth client was successfully created." }
        format.json { render :show, status: :created, location: @oauth_client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oauth_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oauth_clients/1 or /oauth_clients/1.json
  def update
    respond_to do |format|
      if @oauth_client.update(oauth_client_params)
        format.html { redirect_to oauth_client_url(@oauth_client), notice: "Oauth client was successfully updated." }
        format.json { render :show, status: :ok, location: @oauth_client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oauth_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oauth_clients/1 or /oauth_clients/1.json
  def destroy
    @oauth_client.destroy

    respond_to do |format|
      format.html { redirect_to oauth_clients_url, notice: "Oauth client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oauth_client
      @oauth_client = OauthClient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oauth_client_params
      params.require(:oauth_client).permit(:name, :app_id, :app_secret)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/oauth_clients_helper.rb
module OauthClientsHelper
end

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OneSsoProvider
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %main.container.mx-auto.mt-28.px-5.flex
      = yield
      = link_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo: 'false' }

    %footer
      %p.notice= notice
      %p.alert= alert

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OneSsoProvider
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %main.container.mx-auto.mt-28.px-5.flex
      = yield

    %footer
      %p.notice= notice
      %p.alert= alert

app/views/oauth_clients/_form.html.haml
= form_for @oauth_client do |f|
  - if @oauth_client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@oauth_client.errors.count, "error")} prohibited this oauth_client from being saved:"
      %ul
        - @oauth_client.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :app_id
    = f.text_field :app_id
  .field
    = f.label :app_secret
    = f.text_field :app_secret
  .actions
    = f.submit 'Save'

app/views/oauth_clients/edit.html.haml
%h1 Editing oauth_client

= render 'form'

= link_to 'Show', @oauth_client
\|
= link_to 'Back', oauth_clients_path

app/views/oauth_clients/index.html.haml
%h1 Listing oauth_clients

%table
  %thead
    %tr
      %th Name
      %th App
      %th App secret
      %th
      %th
      %th

  %tbody
    - @oauth_clients.each do |oauth_client|
      %tr
        %td= oauth_client.name
        %td= oauth_client.app_id
        %td= oauth_client.app_secret
        %td= link_to 'Show', oauth_client
        %td= link_to 'Edit', edit_oauth_client_path(oauth_client)
        %td= link_to 'Destroy', oauth_client, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Oauth client', new_oauth_client_path

app/views/oauth_clients/new.html.haml
%h1 New oauth_client

= render 'form'

= link_to 'Back', oauth_clients_path

app/views/oauth_clients/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @oauth_client.name
%p
  %b App:
  = @oauth_client.app_id
%p
  %b App secret:
  = @oauth_client.app_secret

= link_to 'Edit', edit_oauth_client_path(@oauth_client)
\|
= link_to 'Back', oauth_clients_path